package subway.domain;

import javax.persistence.*;

/**
 * create table station (
 *     id bigint generated by default as identity,
 *     name varchar(255) not null,
 *     primary key (id)
 * )
 */
@Entity
public class Station {
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false)
    private String name;

    public Line getLine() {
        return line;
    }

    @ManyToOne
    private Line line;

    protected Station() {

    }

    public Station(String name) {
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public void changeName(String name) {
        this.name = name;
    }

    public void setLine(final Line line) {
        this.line = line;
        line.getStation().add(this);
    }
}
